- COPYING.MIT
Signed-off-by: Ruslan Shymkevych <ruslan_shymkevych@epam.com>
> Add MIT license

- recipes-aos/aos-certificatemanager/aos-certificatemanager_git.bbappend
- recipes-aos/aos-certificatemanager/files/aos-certificatemanager.service
- recipes-aos/aos-certificatemanager/files/aos_certificatemanager.cfg
- recipes-aos/aos-servicemanager/files/aos-servicemanager.service
- recipes-aos/aos-servicemanager/files/aos_servicemanager.cfg
- recipes-aos/aos-updatemanager/files/aos_updatemanager.cfg
- recipes-core/images/aos-image-minimal.bb
> Integrate CM

- recipes-core/base-files/base-files/fstab
> [fstab] Mount rootfs as ro file system

- recipes-core/images/aos-image-minimal.inc
> [aos-image-minimal] Make board model configurable

- recipes-aos/aos-iamanager/files/aos-iamanager.service
- recipes-aos/aos-servicemanager/files/aos-servicemanager.service
- recipes-aos/aos-updatemanager/files/aos-updatemanager.service
Signed-off-by: Oleksandr Grytsov <oleksandr_grytsov@epam.com>
> [SM, UM, IAM] Redirect logs to the systemd journal

- doc/local.conf
- recipes-aos/aos-servicemanager/aos-servicemanager_git.bbappend
Signed-off-by: Leonid Komarianskyi <leonid_komarianskyi@epam.com>
> [SM] Make crun as default runtime for AoS services

- recipes-containers/runc/files/0001-Makefile-respect-GOBUILDFLAGS-for-runc-and-remove-re.patch
- recipes-containers/runc/files/0001-runc-Add-console-socket-dev-null-rc93.patch
- recipes-containers/runc/files/0001-runc-docker-SIGUSR1-daemonize-rc93.patch
- recipes-containers/runc/runc-docker_git.bbappend
- recipes-kernel/linux/files/cmdline_append.cfg
- recipes-kernel/linux/linux-yocto_%.bbappend
Signed-off-by: Leonid Komarianskyi <leonid_komarianskyi@epam.com>
> [wic] Switch to cgroup v2

- recipes-aos/aos-servicemanager/files/aos_servicemanager.cfg
- recipes-aos/aos-updatemanager/files/aos_updatemanager.cfg
Signed-off-by: Yevgen Abramov <yevgen_abramov@epam.com>
> [sm] Remove fcrypt from config

- recipes-aos/aos-communicationmanager/files/aos_communicationmanager.cfg
Signed-off-by: Yevgen Abramov <yevgen_abramov@epam.com>
> [cm] Change config to support update schedling

- recipes-aos/aos-communicationmanager/files/aos_communicationmanager.cfg
Signed-off-by: Yevgen Abramov <yevgen_abramov@epam.com>
> Fix cfg alignment

- README.md
- doc/Dockerfile
- doc/run_docker.sh
Signed-off-by: Dmytro Rozzuvailo <dmytro_rozzuvailo@epam.com>
reviewers: @al1img @MykolaSolyanko @Eabramov84
> [build] Docker build environment for building VM

- doc/run_docker.sh
Fix docker run script 
reviewers: @al1img @MykolaSolyanko @Eabramov84
> Fix script run_docker.sh

- recipes-aos-layers/vim-layer/vim-layer.bb
Signed-off-by: Mykola Solianko <mykola_solianko@epam.com>
> [layers] Add vim layer sample with whiteouts

- recipes-core/systemd/systemd-conf/journald_persist.conf
> [journal] Do not split journal files per user

- wic/aos-vm.wks.in
> [wic] Add tty0 console to support virtual box

- recipes-core/images/aos-image-update.bb
Signed-off-by: Mykola Solianko <mykola_solianko@epam.com>
> [aos-image-update] Update bundle component id

- doc/aos_unit_single_node.cfg
> Add unit config for single node vm

- aos-vm.yaml
> Bump v4.0.1

- doc/aos_unit.cfg
> Add vis as resource for node0

- meta-aos-vm-common/recipes-kernel/linux/files/common_node.cfg
Signed-off-by: Mykola Solianko <mykola_solianko@epam.com>
> Add vxlan support  in kernel

- meta-aos-vm-main/recipes-aos/aos-updatemanager/files/aos_updatemanager.cfg
- meta-aos-vm-node/recipes-aos/aos-updatemanager/files/aos_updatemanager.cfg
Signed-off-by: Oleksandr Grytsov <oleksandr_grytsov@epam.com>
> [main, node] Add missing partitions prefixes to UM config

- meta-aos-vm-main/recipes-aos/aos-updatemanager/files/aos_updatemanager.cfg
- meta-aos-vm-node/recipes-aos/aos-updatemanager/files/aos_updatemanager.cfg
Signed-off-by: Oleksandr Grytsov <oleksandr_grytsov@epam.com>
> Hot fix for R4.0.3

- aos-vm.yaml
- meta-aos-vm-common/recipes-core/images/aos-image-initramfs.bbappend
SE linux doesn't work properly for this build.
Looks like changes in refpolicy needed.
Nodes are provisioned successfully in permissive mode
> [scarthgap] Build aos-vm with scarthgap repos

- meta-aos-vm-common/recipes-core/images/aos-image-initramfs.bbappend
With new yocto version current amount is not enough.
> [recipes-core] Increase initramfs RAM to 256Mb
